spring:
  application:
    name: db-edu
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT:3307}/db_edu?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&serverTimezone=Asia/Seoul
    username: db_edu
    password: db_edu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: off
